version: '3.1'
services:
  payment:
    build: machine-app
    ports:
      - '11000:80'
    volumes:
      - './machine-app/machine:/code'
      - './db_volume:/volume'
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_SQLITE_DATABASE_URI}
      LOG_CONFIG_FILENAME: ${LOG_CONFIG_FILENAME}
    restart: on-failure

